openapi: 3.0.0
info:
  title: Funds
  version: '1.0'
  contact:
    name: nat
    email: nat.christanto@email.ottodigital.id
  description: 'API to conduct transaction using a source of funds  '
servers:
  - url: 'https://gateway-dev.ottodigital.id/funds'
    description: funds
paths:
  '/ottocash/payments/{sof_id}':
    parameters:
      - schema:
          type: string
        name: sof_id
        in: path
        description: a transaction id which resulted from a successful payment
        required: true
    get:
      summary: Get payment details
      operationId: get-ottocash-payment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/payment-response'
              examples:
                payment-success:
                  value:
                    response_code: G0000
                    response_message: SUCCESS
                    meta:
                      debug_param: ''
                    account_number: '085780873248'
                    trace_id: blr-231-890
                    product_details:
                      product_code: SIMANIS
                      product_name: Pembelian Emas
                      billing_group: INVESTMENT
                    references:
                      app_reference_number: PEDE-89011234
                      app_code: PEDE
                      user_api_key: cd78h1loenuxmq
                      sof_id: 231
                      sof_reference_number: B789kuolpsw3
                    money:
                      amount: 8000
                      fee: 0
                    description: buy a digital gold
                    transaction_date: '2020-02-26T07:48:00'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
              examples:
                payment-not-found:
                  value:
                    account_number: ''
                    response_code: G0002
                    response_message: Payment ID not found
                    meta:
                      debug_param: wrong payment id
                    trace_id: 8B45E57B2D28BC4C238BEC01BCC68796
      description: get a detail information of an accomplished transaction
      security:
        - client-grant: []
      tags:
        - transaction
  /ottocash/payments:
    post:
      summary: Perform a payment using ottocash
      operationId: ottocash-payment-post
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/payment-response'
              examples:
                payment-success:
                  value:
                    response_code: G0000
                    response_message: SUCCESS
                    meta:
                      debug_param: ''
                    account_number: '085780873248'
                    trace_id: blr-231-890
                    product_details:
                      product_code: SIMANIS
                      product_name: Pembelian Emas
                      billing_group: INVESTMENT
                    references:
                      app_reference_number: PEDE-89011234
                      app_code: PEDE
                      user_api_key: cd78h1loenuxmq
                      sof_id: 231
                      sof_reference_number: B789kuolpsw3
                    money:
                      amount: 8000
                      fee: 0
                    description: buy a digital gold
                    transaction_date: '2020-02-26T07:48:00'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
              examples:
                error-payment-sample:
                  value:
                    account_number: '08129489292'
                    response_code: G0001
                    response_message: Internal error occured
                    meta:
                      debug_param: HMAC verification failed
                    trace_id: 8B45E57B2D28BC4C238BEC01BCC68796
      description: create a payment request to ottocash server
      security:
        - client-grant: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payment-request'
            examples:
              payment-req-sample:
                value:
                  account_number: '085780873248'
                  trace_id: blr-231-890
                  product_details:
                    product_code: SIMANIS
                    product_name: Pembelian Emas
                    billing_group: INVESTMENT
                  references:
                    app_reference_number: PEDE-89011234
                    app_code: PEDE
                    user_api_key: cd78h1loenuxmq
                  money:
                    amount: 8000
                    fee: 0
                  credentials:
                    password:
                      key_version: 2
                      value: 0bGKqoTexw7QAt0OpuCHHMwMpadqKuSCDaOhjiGkL7cdxCxROlQR2yfg3YDz44MeqwP8fe+l45GvGvDyjE7g5LVQMAxDyaA+2HENSlKkEExS+uHfjYcxjbCBlwEbMPf9zS3cKYHA2PbHNxpa8Aubr9KkBENxORqB2zzw0e0HmSMHJu1kcWA9M1AIFIpPSiCTJuCmg3E4KNzShFlP5LbBiOWtQhHts4G7geSgUtgWuv4=
                      format: aes-cbc
                  description: buy a gold
        description: A payment request
      tags:
        - transaction
  /users:
    post:
      summary: create a new user-api-key
      operationId: post-users
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_api_key:
                    type: string
                  response_code:
                    type: string
                  response_message:
                    type: string
                  meta:
                    $ref: '#/components/schemas/meta'
                  trace_id:
                    type: string
              examples:
                user-response:
                  value:
                    response_code: G0000
                    response_message: SUCCESS
                    user_api_key: 8uoaopsmd0
                    meta:
                      debug_param: ''
                    trace_id: 890hjukolpoyuio
      description: create a new user which resulted a new user-api-key
      security:
        - client-grant: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                app_code:
                  type: string
                trace_id:
                  type: string
              required:
                - app_code
                - trace_id
            examples:
              create-user-example:
                value:
                  app_code: PEDE
        description: ''
      tags:
        - user
components:
  schemas:
    payment-request:
      title: payment-request
      type: object
      description: a payment request model
      properties:
        account_number:
          type: string
          description: fill it with mobile phone number
        trace_id:
          type: string
          description: it should be defined unique for debugging purpose
        product_details:
          type: object
          required:
            - product_name
            - billing_group
            - product_code
          properties:
            product_name:
              type: string
              description: refer to product name which defined by ottocash
            billing_group:
              type: string
              description: refer to billing id which defined by ottocash
            product_code:
              type: string
              description: refere to product code which defined by ottocash
        references:
          type: object
          required:
            - app_reference_number
            - app_code
            - user_api_key
          properties:
            app_reference_number:
              type: string
              description: this reference will be used for reverse purpose
            app_code:
              type: string
            user_api_key:
              type: string
        credentials:
          type: object
          required:
            - password
          properties:
            password:
              type: object
              required:
                - key_version
                - format
                - value
              properties:
                key_version:
                  type: string
                format:
                  type: string
                value:
                  type: string
        money:
          type: object
          required:
            - amount
            - fee
          properties:
            amount:
              type: integer
            fee:
              type: integer
        description:
          type: string
      required:
        - account_number
        - trace_id
        - product_details
        - references
        - credentials
        - money
        - description
    payment-response:
      title: payment-response
      type: object
      description: a response after successfully capturing a payment
      properties:
        response_code:
          type: string
        response_message:
          type: string
        meta:
          $ref: '#/components/schemas/meta'
        trace_id:
          type: string
        account_number:
          type: string
        product_details:
          type: object
          properties:
            product_code:
              type: string
            product_name:
              type: string
            billing_group:
              type: string
        money:
          type: object
          properties:
            amount:
              type: integer
            fee:
              type: integer
        references:
          type: object
          properties:
            app_reference_number:
              type: string
            app_code:
              type: string
            sof_id:
              type: integer
            sof_reference_number:
              type: string
            user_api_key:
              type: string
        transaction_date:
          type: string
    meta:
      title: meta
      type: object
      description: 'Meta struct for additional details. Might be used for troubleshooting, etc'
      properties:
        debug_param:
          type: string
    error-response:
      title: error-response
      type: object
      description: a general error response
      properties:
        account_number:
          type: string
        response_code:
          type: string
        response_message:
          type: string
        trace_id:
          type: string
        meta:
          $ref: '#/components/schemas/meta'
  securitySchemes:
    client-grant:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://token.ottodigital.id'
          scopes:
            read: read a resource
            write: write a resource
          refreshUrl: 'https://refresh.ottodigital.id'
      description: a grant access that will be used by partner
tags:
  - name: user
  - name: transaction
