openapi: 3.0.0
info:
  title: Funds
  version: '1.0'
  contact:
    name: nat
    email: nat.christanto@email.ottodigital.id
  description: 'API to conduct transaction using a source of funds  '
servers:
  - url: 'https://funds.ottodigital.id'
    description: funds
paths:
  /transactions:
    post:
      summary: Payment
      operationId: post-transactions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/default-response'
              examples: {}
      description: 'perform payment transaction '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/journal'
            examples: {}
          application/xml:
            schema:
              type: object
              properties: {}
        description: it will be described later
      security:
        - client-token: []
      tags:
        - debit
  /reversal:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-reversal
      description: perform a reversal of transaction
  /credentials/validate:
    parameters: []
    post:
      summary: Pin Check
      operationId: password-checking
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/default-response'
              examples:
                sample-pin-response:
                  value:
                    responseDescription: SUCCEED
                    referenceNumber: '911800002545'
                    transactionDate: '20190218102818'
                    responseCode: '00'
      description: validate a user credential
      security:
        - client-token: []
      tags:
        - credentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credential'
            examples:
              pin-request:
                value:
                  mobile_phone_number: '081234588991'
                  institution_code: PEDE
                  pin: '123456'
        description: ''
components:
  schemas:
    journal:
      title: journal
      type: object
      properties:
        mobile_phone_number:
          type: string
        amount:
          type: integer
        fee:
          type: integer
        product_name:
          type: string
        biller_id:
          type: string
        customer_referencce_number:
          type: string
        product_code:
          type: string
        partner_code:
          type: string
      x-examples:
        sample-payment-request:
          accountNumber: '085780873248'
          amount: '95000'
          fee: '5000'
          productName: Pembayaran Barang
          billerId: PURCHASE_ELEVENIA
          customerReferenceNumber: UPN000000457
          productCode: PYMNT
          partnerCode: P000001
    default-response:
      title: default-response
      type: object
      description: a general response of Funds API
      properties:
        response_description:
          type: string
        response_code:
          type: string
        transaction_date:
          type: string
        reference_number:
          type: string
      x-examples:
        default-sample-response:
          responseDescription: SUCCEED
          referenceNumber: '911800002545'
          transactionDate: '20190218102818'
          responseCode: '00'
    credential:
      title: credential
      type: object
      properties:
        mobile_phone_number:
          type: string
        institution_code:
          type: string
        pin:
          type: string
      x-examples:
        pin-sample:
          mobile_phone_number: '081234588991'
          institution_code: PEDE
          pin: '123456'
      description: pin
  securitySchemes:
    client-token:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
tags:
  - name: debit
  - name: credentials
