openapi: 3.0.0
info:
  title: Funds
  version: '1.0'
  contact:
    name: nat
    email: nat.christanto@email.ottodigital.id
  description: 'API to conduct transaction using a source of funds  '
servers:
  - url: 'https://funds.ottodigital.id'
    description: funds
paths:
  /payments:
    post:
      summary: Payment
      operationId: post-transactions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/journal-response'
              examples: {}
      description: create a payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payment-request'
            examples:
              payment-req-sample:
                value:
                  mobile_phone_number: '085780873248'
                  amount: '95000'
                  fee: '5000'
                  product_name: Pembayaran Barang
                  biller_id: PURCHASE_ELEVENIA
                  customer_reference_number: UPN000000457
                  product_code: PYMNT
                  partner_code: P000001
          application/xml:
            schema:
              type: object
              properties: {}
        description: it will be described later
      security:
        - client-token: []
      tags:
        - debit
    parameters: []
  /reversal:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-reversal
      description: perform a reversal of transaction
  /credentials/validate:
    parameters: []
    post:
      summary: Pin Check
      operationId: password-checking
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/journal-response'
              examples:
                sample-pin-response:
                  value:
                    responseDescription: SUCCEED
                    referenceNumber: '911800002545'
                    transactionDate: '20190218102818'
                    responseCode: '00'
      description: validate a user credential
      security:
        - client-token: []
      tags:
        - credentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credential'
            examples:
              pin-request:
                value:
                  mobile_phone_number: '081234588991'
                  institution_code: PEDE
                  pin: '123456'
        description: ''
components:
  schemas:
    payment-request:
      title: payment-request
      type: object
      x-examples:
        sample-payment-request:
          mobile_phone_number: '085780873248'
          amount: '95000'
          fee: '5000'
          product_name: Pembayaran Barang
          biller_id: PURCHASE_ELEVENIA
          customer_reference_number: UPN000000457
          product_code: PYMNT
          partner_code: P000001
      description: a model to conduct payment
      properties:
        mobile_phone_number:
          type: string
        trace_id:
          type: string
        product_details:
          type: object
          required:
            - product_name
            - billing_group
            - product_code
          properties:
            product_name:
              type: string
            billing_group:
              type: string
            product_code:
              type: string
        references:
          type: object
          required:
            - app_reference_number
            - app_code
          properties:
            app_reference_number:
              type: string
            app_code:
              type: string
        credential:
          type: object
          properties:
            password:
              type: object
              properties:
                key_version:
                  type: string
                format:
                  type: string
                value:
                  type: string
        money:
          type: object
          properties:
            amount:
              type: integer
            fee:
              type: integer
      required:
        - mobile_phone_number
        - trace_id
        - product_details
        - references
    journal-response:
      title: default-response
      type: object
      description: a general response of Funds API
      properties:
        response_description:
          type: string
        response_code:
          type: string
        transaction_date:
          type: string
        reference_number:
          type: string
      x-examples:
        default-sample-response:
          responseDescription: SUCCEED
          referenceNumber: '911800002545'
          transactionDate: '20190218102818'
          responseCode: '00'
    credential:
      title: credential
      type: object
      properties:
        mobile_phone_number:
          type: string
        institution_code:
          type: string
        pin:
          type: string
      x-examples:
        pin-sample:
          mobile_phone_number: '081234588991'
          institution_code: PEDE
          pin: '123456'
      description: pin
    payment-response:
      title: payment-response
      type: object
      description: a response after successfully capturing a payment
      properties:
        response_code:
          type: string
        response_message:
          type: string
        meta:
          $ref: '#/components/schemas/meta'
        trace_id:
          type: string
        mobile_phone_number:
          type: string
        product_details:
          type: object
          properties:
            product_code:
              type: string
            product_name:
              type: string
            billing_group:
              type: string
        '':
          type: string
    meta:
      title: meta
      type: object
      properties:
        debug_param:
          type: string
        '':
          type: string
  securitySchemes:
    client-token:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
tags:
  - name: debit
  - name: credentials
